sudo: required

# https://github.com/travis-ci/docs-travis-ci-com/issues/910#issuecomment-356915625
language: minimal

services:
  - docker

before_install:
  - docker build -t vitarn/dynalite .

script:
  - docker image ls
