sudo: required

language: node_js

services:
  - docker

before_install:
  - docker build -t vitarn/dynalite .

script:
  - docker image ls

# after_success:
#   - if [ "$TRAVIS_BRANCH" == "master" ]; then
#       docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
#       docker push vitarn/dynalite;
#     fi
